# Generated by Django 5.0.3 on 2024-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
