# Generated by Django 5.0.3 on 2024-03-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
